package me.xdan.motif.ui.theme

import androidx.compose.ui.graphics.Color

val MotifTealLight = Color(0xFF006A6D)
val MotifOnTealLight = Color(0xFFFFFFFF)
val MotifTealContainerLight = Color(0xFF9CF1F2)
val MotifOnTealContainerLight = Color(0xFF002021)
val MotifCoralLight = Color(0xFF8F4C3E)
val MotifOnCoralLight = Color(0xFFFFFFFF)
val MotifCoralContainerLight = Color(0xFFFFDAD1)
val MotifOnCoralContainerLight = Color(0xFF3A0B04)
val MotifMintLight = Color(0xFF4D635F)
val MotifOnMintLight = Color(0xFFFFFFFF)
val MotifMintContainerLight = Color(0xFFCFE9E3)
val MotifOnMintContainerLight = Color(0xFF09201D)
val MotifBackgroundLight = Color(0xFFFFF8F6)
val MotifOnBackgroundLight = Color(0xFF1F1B1A)
val MotifSurfaceLight = Color(0xFFFFF8F6)
val MotifSurfaceVariantLight = Color(0xFFDAE5E2)
val MotifOnSurfaceVariantLight = Color(0xFF3F4947)
val MotifOutlineLight = Color(0xFF6F7977)

val MotifTealDark = Color(0xFF80D5D6)
val MotifOnTealDark = Color(0xFF003738)
val MotifTealContainerDark = Color(0xFF004F51)
val MotifOnTealContainerDark = Color(0xFF9CF1F2)
val MotifCoralDark = Color(0xFFFFB4A4)
val MotifOnCoralDark = Color(0xFF561F15)
val MotifCoralContainerDark = Color(0xFF73352A)
val MotifOnCoralContainerDark = Color(0xFFFFDAD1)
val MotifMintDark = Color(0xFFB3CCC7)
val MotifOnMintDark = Color(0xFF1F3531)
val MotifMintContainerDark = Color(0xFF354B47)
val MotifOnMintContainerDark = Color(0xFFCFE9E3)
val MotifBackgroundDark = Color(0xFF161312)
val MotifOnBackgroundDark = Color(0xFFECE0DD)
val MotifSurfaceDark = Color(0xFF161312)
val MotifSurfaceVariantDark = Color(0xFF3F4947)
val MotifOnSurfaceVariantDark = Color(0xFFBEC9C6)
val MotifOutlineDark = Color(0xFF899390)
